/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables.records;


import eu.dissco.backend.database.jooq.tables.Annotation;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnnotationRecord extends UpdatableRecordImpl<AnnotationRecord> implements Record7<String, String, JSONB, String, Instant, String, Instant> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.annotation.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.annotation.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.annotation.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.annotation.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.annotation.body</code>.
     */
    public void setBody(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.annotation.body</code>.
     */
    public JSONB getBody() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.annotation.target</code>.
     */
    public void setTarget(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.annotation.target</code>.
     */
    public String getTarget() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.annotation.last_updated</code>.
     */
    public void setLastUpdated(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.annotation.last_updated</code>.
     */
    public Instant getLastUpdated() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.annotation.creator</code>.
     */
    public void setCreator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.annotation.creator</code>.
     */
    public String getCreator() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.annotation.created</code>.
     */
    public void setCreated(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.annotation.created</code>.
     */
    public Instant getCreated() {
        return (Instant) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, JSONB, String, Instant, String, Instant> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<String, String, JSONB, String, Instant, String, Instant> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Annotation.ANNOTATION.ID;
    }

    @Override
    public Field<String> field2() {
        return Annotation.ANNOTATION.TYPE;
    }

    @Override
    public Field<JSONB> field3() {
        return Annotation.ANNOTATION.BODY;
    }

    @Override
    public Field<String> field4() {
        return Annotation.ANNOTATION.TARGET;
    }

    @Override
    public Field<Instant> field5() {
        return Annotation.ANNOTATION.LAST_UPDATED;
    }

    @Override
    public Field<String> field6() {
        return Annotation.ANNOTATION.CREATOR;
    }

    @Override
    public Field<Instant> field7() {
        return Annotation.ANNOTATION.CREATED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getType();
    }

    @Override
    public JSONB component3() {
        return getBody();
    }

    @Override
    public String component4() {
        return getTarget();
    }

    @Override
    public Instant component5() {
        return getLastUpdated();
    }

    @Override
    public String component6() {
        return getCreator();
    }

    @Override
    public Instant component7() {
        return getCreated();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getType();
    }

    @Override
    public JSONB value3() {
        return getBody();
    }

    @Override
    public String value4() {
        return getTarget();
    }

    @Override
    public Instant value5() {
        return getLastUpdated();
    }

    @Override
    public String value6() {
        return getCreator();
    }

    @Override
    public Instant value7() {
        return getCreated();
    }

    @Override
    public AnnotationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AnnotationRecord value2(String value) {
        setType(value);
        return this;
    }

    @Override
    public AnnotationRecord value3(JSONB value) {
        setBody(value);
        return this;
    }

    @Override
    public AnnotationRecord value4(String value) {
        setTarget(value);
        return this;
    }

    @Override
    public AnnotationRecord value5(Instant value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public AnnotationRecord value6(String value) {
        setCreator(value);
        return this;
    }

    @Override
    public AnnotationRecord value7(Instant value) {
        setCreated(value);
        return this;
    }

    @Override
    public AnnotationRecord values(String value1, String value2, JSONB value3, String value4, Instant value5, String value6, Instant value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnnotationRecord
     */
    public AnnotationRecord() {
        super(Annotation.ANNOTATION);
    }

    /**
     * Create a detached, initialised AnnotationRecord
     */
    public AnnotationRecord(String id, String type, JSONB body, String target, Instant lastUpdated, String creator, Instant created) {
        super(Annotation.ANNOTATION);

        setId(id);
        setType(type);
        setBody(body);
        setTarget(target);
        setLastUpdated(lastUpdated);
        setCreator(creator);
        setCreated(created);
    }
}
