/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables.records;


import eu.dissco.backend.database.jooq.enums.Curatedobjectidtypes;
import eu.dissco.backend.database.jooq.tables.DigitalSpecimen;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigitalSpecimenRecord extends UpdatableRecordImpl<DigitalSpecimenRecord> implements Record9<String, String, String, Short, Curatedobjectidtypes, String, String, String, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.digital_specimen.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.digital_specimen.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.digital_specimen.object_type</code>.
     */
    public void setObjectType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.digital_specimen.object_type</code>.
     */
    public String getObjectType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.digital_specimen.curated_object_id</code>.
     */
    public void setCuratedObjectId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.digital_specimen.curated_object_id</code>.
     */
    public String getCuratedObjectId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.digital_specimen.mids_level</code>.
     */
    public void setMidsLevel(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.digital_specimen.mids_level</code>.
     */
    public Short getMidsLevel() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.digital_specimen.curated_object_id_type</code>.
     */
    public void setCuratedObjectIdType(Curatedobjectidtypes value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.digital_specimen.curated_object_id_type</code>.
     */
    public Curatedobjectidtypes getCuratedObjectIdType() {
        return (Curatedobjectidtypes) get(4);
    }

    /**
     * Setter for <code>public.digital_specimen.specimen_name</code>.
     */
    public void setSpecimenName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.digital_specimen.specimen_name</code>.
     */
    public String getSpecimenName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.digital_specimen.institution_id</code>.
     */
    public void setInstitutionId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.digital_specimen.institution_id</code>.
     */
    public String getInstitutionId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.digital_specimen.institution_name</code>.
     */
    public void setInstitutionName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.digital_specimen.institution_name</code>.
     */
    public String getInstitutionName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.digital_specimen.data</code>.
     */
    public void setData(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.digital_specimen.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, Short, Curatedobjectidtypes, String, String, String, JSONB> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, Short, Curatedobjectidtypes, String, String, String, JSONB> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.ID;
    }

    @Override
    public Field<String> field2() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.OBJECT_TYPE;
    }

    @Override
    public Field<String> field3() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.CURATED_OBJECT_ID;
    }

    @Override
    public Field<Short> field4() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.MIDS_LEVEL;
    }

    @Override
    public Field<Curatedobjectidtypes> field5() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.CURATED_OBJECT_ID_TYPE;
    }

    @Override
    public Field<String> field6() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.SPECIMEN_NAME;
    }

    @Override
    public Field<String> field7() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.INSTITUTION_ID;
    }

    @Override
    public Field<String> field8() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.INSTITUTION_NAME;
    }

    @Override
    public Field<JSONB> field9() {
        return DigitalSpecimen.DIGITAL_SPECIMEN.DATA;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getObjectType();
    }

    @Override
    public String component3() {
        return getCuratedObjectId();
    }

    @Override
    public Short component4() {
        return getMidsLevel();
    }

    @Override
    public Curatedobjectidtypes component5() {
        return getCuratedObjectIdType();
    }

    @Override
    public String component6() {
        return getSpecimenName();
    }

    @Override
    public String component7() {
        return getInstitutionId();
    }

    @Override
    public String component8() {
        return getInstitutionName();
    }

    @Override
    public JSONB component9() {
        return getData();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getObjectType();
    }

    @Override
    public String value3() {
        return getCuratedObjectId();
    }

    @Override
    public Short value4() {
        return getMidsLevel();
    }

    @Override
    public Curatedobjectidtypes value5() {
        return getCuratedObjectIdType();
    }

    @Override
    public String value6() {
        return getSpecimenName();
    }

    @Override
    public String value7() {
        return getInstitutionId();
    }

    @Override
    public String value8() {
        return getInstitutionName();
    }

    @Override
    public JSONB value9() {
        return getData();
    }

    @Override
    public DigitalSpecimenRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value2(String value) {
        setObjectType(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value3(String value) {
        setCuratedObjectId(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value4(Short value) {
        setMidsLevel(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value5(Curatedobjectidtypes value) {
        setCuratedObjectIdType(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value6(String value) {
        setSpecimenName(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value7(String value) {
        setInstitutionId(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value8(String value) {
        setInstitutionName(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord value9(JSONB value) {
        setData(value);
        return this;
    }

    @Override
    public DigitalSpecimenRecord values(String value1, String value2, String value3, Short value4, Curatedobjectidtypes value5, String value6, String value7, String value8, JSONB value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DigitalSpecimenRecord
     */
    public DigitalSpecimenRecord() {
        super(DigitalSpecimen.DIGITAL_SPECIMEN);
    }

    /**
     * Create a detached, initialised DigitalSpecimenRecord
     */
    public DigitalSpecimenRecord(String id, String objectType, String curatedObjectId, Short midsLevel, Curatedobjectidtypes curatedObjectIdType, String specimenName, String institutionId, String institutionName, JSONB data) {
        super(DigitalSpecimen.DIGITAL_SPECIMEN);

        setId(id);
        setObjectType(objectType);
        setCuratedObjectId(curatedObjectId);
        setMidsLevel(midsLevel);
        setCuratedObjectIdType(curatedObjectIdType);
        setSpecimenName(specimenName);
        setInstitutionId(institutionId);
        setInstitutionName(institutionName);
        setData(data);
    }
}
