/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables.records;


import eu.dissco.backend.database.jooq.enums.MjrJobState;
import eu.dissco.backend.database.jooq.enums.MjrTargetType;
import eu.dissco.backend.database.jooq.tables.MasJobRecordTmp;

import java.time.Instant;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MasJobRecordTmpRecord extends UpdatableRecordImpl<MasJobRecordTmpRecord> implements Record10<String, MjrJobState, String, Instant, Instant, JSONB, String, String, MjrTargetType, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mas_job_record_tmp.job_id</code>.
     */
    public void setJobId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.job_id</code>.
     */
    public String getJobId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.job_state</code>.
     */
    public void setJobState(MjrJobState value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.job_state</code>.
     */
    public MjrJobState getJobState() {
        return (MjrJobState) get(1);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.mas_id</code>.
     */
    public void setMasId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.mas_id</code>.
     */
    public String getMasId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.time_started</code>.
     */
    public void setTimeStarted(Instant value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.time_started</code>.
     */
    public Instant getTimeStarted() {
        return (Instant) get(3);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.time_completed</code>.
     */
    public void setTimeCompleted(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.time_completed</code>.
     */
    public Instant getTimeCompleted() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.annotations</code>.
     */
    public void setAnnotations(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.annotations</code>.
     */
    public JSONB getAnnotations() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.target_id</code>.
     */
    public void setTargetId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.target_id</code>.
     */
    public String getTargetId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.user_id</code>.
     */
    public void setUserId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.user_id</code>.
     */
    public String getUserId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.target_type</code>.
     */
    public void setTargetType(MjrTargetType value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.target_type</code>.
     */
    public MjrTargetType getTargetType() {
        return (MjrTargetType) get(8);
    }

    /**
     * Setter for <code>public.mas_job_record_tmp.batching_requested</code>.
     */
    public void setBatchingRequested(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mas_job_record_tmp.batching_requested</code>.
     */
    public Boolean getBatchingRequested() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, MjrJobState, String, Instant, Instant, JSONB, String, String, MjrTargetType, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, MjrJobState, String, Instant, Instant, JSONB, String, String, MjrTargetType, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.JOB_ID;
    }

    @Override
    public Field<MjrJobState> field2() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.JOB_STATE;
    }

    @Override
    public Field<String> field3() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.MAS_ID;
    }

    @Override
    public Field<Instant> field4() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.TIME_STARTED;
    }

    @Override
    public Field<Instant> field5() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.TIME_COMPLETED;
    }

    @Override
    public Field<JSONB> field6() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.ANNOTATIONS;
    }

    @Override
    public Field<String> field7() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.TARGET_ID;
    }

    @Override
    public Field<String> field8() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.USER_ID;
    }

    @Override
    public Field<MjrTargetType> field9() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.TARGET_TYPE;
    }

    @Override
    public Field<Boolean> field10() {
        return MasJobRecordTmp.MAS_JOB_RECORD_TMP.BATCHING_REQUESTED;
    }

    @Override
    public String component1() {
        return getJobId();
    }

    @Override
    public MjrJobState component2() {
        return getJobState();
    }

    @Override
    public String component3() {
        return getMasId();
    }

    @Override
    public Instant component4() {
        return getTimeStarted();
    }

    @Override
    public Instant component5() {
        return getTimeCompleted();
    }

    @Override
    public JSONB component6() {
        return getAnnotations();
    }

    @Override
    public String component7() {
        return getTargetId();
    }

    @Override
    public String component8() {
        return getUserId();
    }

    @Override
    public MjrTargetType component9() {
        return getTargetType();
    }

    @Override
    public Boolean component10() {
        return getBatchingRequested();
    }

    @Override
    public String value1() {
        return getJobId();
    }

    @Override
    public MjrJobState value2() {
        return getJobState();
    }

    @Override
    public String value3() {
        return getMasId();
    }

    @Override
    public Instant value4() {
        return getTimeStarted();
    }

    @Override
    public Instant value5() {
        return getTimeCompleted();
    }

    @Override
    public JSONB value6() {
        return getAnnotations();
    }

    @Override
    public String value7() {
        return getTargetId();
    }

    @Override
    public String value8() {
        return getUserId();
    }

    @Override
    public MjrTargetType value9() {
        return getTargetType();
    }

    @Override
    public Boolean value10() {
        return getBatchingRequested();
    }

    @Override
    public MasJobRecordTmpRecord value1(String value) {
        setJobId(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value2(MjrJobState value) {
        setJobState(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value3(String value) {
        setMasId(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value4(Instant value) {
        setTimeStarted(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value5(Instant value) {
        setTimeCompleted(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value6(JSONB value) {
        setAnnotations(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value7(String value) {
        setTargetId(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value8(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value9(MjrTargetType value) {
        setTargetType(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord value10(Boolean value) {
        setBatchingRequested(value);
        return this;
    }

    @Override
    public MasJobRecordTmpRecord values(String value1, MjrJobState value2, String value3, Instant value4, Instant value5, JSONB value6, String value7, String value8, MjrTargetType value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MasJobRecordTmpRecord
     */
    public MasJobRecordTmpRecord() {
        super(MasJobRecordTmp.MAS_JOB_RECORD_TMP);
    }

    /**
     * Create a detached, initialised MasJobRecordTmpRecord
     */
    public MasJobRecordTmpRecord(String jobId, MjrJobState jobState, String masId, Instant timeStarted, Instant timeCompleted, JSONB annotations, String targetId, String userId, MjrTargetType targetType, Boolean batchingRequested) {
        super(MasJobRecordTmp.MAS_JOB_RECORD_TMP);

        setJobId(jobId);
        setJobState(jobState);
        setMasId(masId);
        setTimeStarted(timeStarted);
        setTimeCompleted(timeCompleted);
        setAnnotations(annotations);
        setTargetId(targetId);
        setUserId(userId);
        setTargetType(targetType);
        setBatchingRequested(batchingRequested);
        resetChangedOnNotNull();
    }
}
