/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables.records;


import eu.dissco.backend.database.jooq.enums.CollectionType;
import eu.dissco.backend.database.jooq.tables.VirtualCollection;

import java.time.Instant;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VirtualCollectionRecord extends UpdatableRecordImpl<VirtualCollectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.virtual_collection.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.virtual_collection.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.virtual_collection.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.virtual_collection.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.virtual_collection.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.virtual_collection.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.virtual_collection.collection_type</code>.
     */
    public void setCollectionType(CollectionType value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.virtual_collection.collection_type</code>.
     */
    public CollectionType getCollectionType() {
        return (CollectionType) get(3);
    }

    /**
     * Setter for <code>public.virtual_collection.created</code>.
     */
    public void setCreated(Instant value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.virtual_collection.created</code>.
     */
    public Instant getCreated() {
        return (Instant) get(4);
    }

    /**
     * Setter for <code>public.virtual_collection.modified</code>.
     */
    public void setModified(Instant value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.virtual_collection.modified</code>.
     */
    public Instant getModified() {
        return (Instant) get(5);
    }

    /**
     * Setter for <code>public.virtual_collection.tombstoned</code>.
     */
    public void setTombstoned(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.virtual_collection.tombstoned</code>.
     */
    public Instant getTombstoned() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.virtual_collection.creator</code>.
     */
    public void setCreator(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.virtual_collection.creator</code>.
     */
    public String getCreator() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.virtual_collection.data</code>.
     */
    public void setData(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.virtual_collection.data</code>.
     */
    public JSONB getData() {
        return (JSONB) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VirtualCollectionRecord
     */
    public VirtualCollectionRecord() {
        super(VirtualCollection.VIRTUAL_COLLECTION);
    }

    /**
     * Create a detached, initialised VirtualCollectionRecord
     */
    public VirtualCollectionRecord(String id, Integer version, String name, CollectionType collectionType, Instant created, Instant modified, Instant tombstoned, String creator, JSONB data) {
        super(VirtualCollection.VIRTUAL_COLLECTION);

        setId(id);
        setVersion(version);
        setName(name);
        setCollectionType(collectionType);
        setCreated(created);
        setModified(modified);
        setTombstoned(tombstoned);
        setCreator(creator);
        setData(data);
        resetChangedOnNotNull();
    }
}
