/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables;


import eu.dissco.backend.database.jooq.Keys;
import eu.dissco.backend.database.jooq.Public;
import eu.dissco.backend.database.jooq.tables.records.MachineAnnotationServicesTmpRecord;

import java.time.Instant;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function21;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineAnnotationServicesTmp extends TableImpl<MachineAnnotationServicesTmpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.machine_annotation_services_tmp</code>
     */
    public static final MachineAnnotationServicesTmp MACHINE_ANNOTATION_SERVICES_TMP = new MachineAnnotationServicesTmp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MachineAnnotationServicesTmpRecord> getRecordType() {
        return MachineAnnotationServicesTmpRecord.class;
    }

    /**
     * The column <code>public.machine_annotation_services_tmp.id</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.machine_annotation_services_tmp.version</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.machine_annotation_services_tmp.name</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.machine_annotation_services_tmp.created</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, Instant> CREATED = createField(DSL.name("created"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.administrator</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> ADMINISTRATOR = createField(DSL.name("administrator"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.container_image</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> CONTAINER_IMAGE = createField(DSL.name("container_image"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.container_image_tag</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> CONTAINER_IMAGE_TAG = createField(DSL.name("container_image_tag"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.target_digital_object_filters</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, JSONB> TARGET_DIGITAL_OBJECT_FILTERS = createField(DSL.name("target_digital_object_filters"), SQLDataType.JSONB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.service_description</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SERVICE_DESCRIPTION = createField(DSL.name("service_description"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.service_state</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SERVICE_STATE = createField(DSL.name("service_state"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.source_code_repository</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SOURCE_CODE_REPOSITORY = createField(DSL.name("source_code_repository"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.service_availability</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SERVICE_AVAILABILITY = createField(DSL.name("service_availability"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.code_maintainer</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> CODE_MAINTAINER = createField(DSL.name("code_maintainer"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.code_license</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> CODE_LICENSE = createField(DSL.name("code_license"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.dependencies</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String[]> DEPENDENCIES = createField(DSL.name("dependencies"), SQLDataType.CLOB.array(), this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.support_contact</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SUPPORT_CONTACT = createField(DSL.name("support_contact"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.sla_documentation</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> SLA_DOCUMENTATION = createField(DSL.name("sla_documentation"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.machine_annotation_services_tmp.topicname</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, String> TOPICNAME = createField(DSL.name("topicname"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.maxreplicas</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, Integer> MAXREPLICAS = createField(DSL.name("maxreplicas"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.deleted_on</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, Instant> DELETED_ON = createField(DSL.name("deleted_on"), SQLDataType.INSTANT, this, "");

    /**
     * The column
     * <code>public.machine_annotation_services_tmp.batching_permitted</code>.
     */
    public final TableField<MachineAnnotationServicesTmpRecord, Boolean> BATCHING_PERMITTED = createField(DSL.name("batching_permitted"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private MachineAnnotationServicesTmp(Name alias, Table<MachineAnnotationServicesTmpRecord> aliased) {
        this(alias, aliased, null);
    }

    private MachineAnnotationServicesTmp(Name alias, Table<MachineAnnotationServicesTmpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.machine_annotation_services_tmp</code>
     * table reference
     */
    public MachineAnnotationServicesTmp(String alias) {
        this(DSL.name(alias), MACHINE_ANNOTATION_SERVICES_TMP);
    }

    /**
     * Create an aliased <code>public.machine_annotation_services_tmp</code>
     * table reference
     */
    public MachineAnnotationServicesTmp(Name alias) {
        this(alias, MACHINE_ANNOTATION_SERVICES_TMP);
    }

    /**
     * Create a <code>public.machine_annotation_services_tmp</code> table
     * reference
     */
    public MachineAnnotationServicesTmp() {
        this(DSL.name("machine_annotation_services_tmp"), null);
    }

    public <O extends Record> MachineAnnotationServicesTmp(Table<O> child, ForeignKey<O, MachineAnnotationServicesTmpRecord> key) {
        super(child, key, MACHINE_ANNOTATION_SERVICES_TMP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MachineAnnotationServicesTmpRecord> getPrimaryKey() {
        return Keys.MACHINE_ANNOTATION_SERVICES_TMP_PKEY;
    }

    @Override
    public MachineAnnotationServicesTmp as(String alias) {
        return new MachineAnnotationServicesTmp(DSL.name(alias), this);
    }

    @Override
    public MachineAnnotationServicesTmp as(Name alias) {
        return new MachineAnnotationServicesTmp(alias, this);
    }

    @Override
    public MachineAnnotationServicesTmp as(Table<?> alias) {
        return new MachineAnnotationServicesTmp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MachineAnnotationServicesTmp rename(String name) {
        return new MachineAnnotationServicesTmp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MachineAnnotationServicesTmp rename(Name name) {
        return new MachineAnnotationServicesTmp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MachineAnnotationServicesTmp rename(Table<?> name) {
        return new MachineAnnotationServicesTmp(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<String, Integer, String, Instant, String, String, String, JSONB, String, String, String, String, String, String, String[], String, String, String, Integer, Instant, Boolean> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function21<? super String, ? super Integer, ? super String, ? super Instant, ? super String, ? super String, ? super String, ? super JSONB, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String[], ? super String, ? super String, ? super String, ? super Integer, ? super Instant, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function21<? super String, ? super Integer, ? super String, ? super Instant, ? super String, ? super String, ? super String, ? super JSONB, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String[], ? super String, ? super String, ? super String, ? super Integer, ? super Instant, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
