/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables;


import eu.dissco.backend.database.jooq.Keys;
import eu.dissco.backend.database.jooq.Public;
import eu.dissco.backend.database.jooq.enums.MjrJobState;
import eu.dissco.backend.database.jooq.enums.MjrTargetType;
import eu.dissco.backend.database.jooq.tables.records.MasJobRecordNewRecord;

import java.time.Instant;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MasJobRecordNew extends TableImpl<MasJobRecordNewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mas_job_record_new</code>
     */
    public static final MasJobRecordNew MAS_JOB_RECORD_NEW = new MasJobRecordNew();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MasJobRecordNewRecord> getRecordType() {
        return MasJobRecordNewRecord.class;
    }

    /**
     * The column <code>public.mas_job_record_new.job_id</code>.
     */
    public final TableField<MasJobRecordNewRecord, String> JOB_ID = createField(DSL.name("job_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_new.job_state</code>.
     */
    public final TableField<MasJobRecordNewRecord, MjrJobState> JOB_STATE = createField(DSL.name("job_state"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(eu.dissco.backend.database.jooq.enums.MjrJobState.class), this, "");

    /**
     * The column <code>public.mas_job_record_new.mas_id</code>.
     */
    public final TableField<MasJobRecordNewRecord, String> MAS_ID = createField(DSL.name("mas_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_new.time_started</code>.
     */
    public final TableField<MasJobRecordNewRecord, Instant> TIME_STARTED = createField(DSL.name("time_started"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_new.time_completed</code>.
     */
    public final TableField<MasJobRecordNewRecord, Instant> TIME_COMPLETED = createField(DSL.name("time_completed"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.mas_job_record_new.annotations</code>.
     */
    public final TableField<MasJobRecordNewRecord, JSONB> ANNOTATIONS = createField(DSL.name("annotations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.mas_job_record_new.target_id</code>.
     */
    public final TableField<MasJobRecordNewRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_new.user_id</code>.
     */
    public final TableField<MasJobRecordNewRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mas_job_record_new.target_type</code>.
     */
    public final TableField<MasJobRecordNewRecord, MjrTargetType> TARGET_TYPE = createField(DSL.name("target_type"), SQLDataType.VARCHAR.asEnumDataType(eu.dissco.backend.database.jooq.enums.MjrTargetType.class), this, "");

    private MasJobRecordNew(Name alias, Table<MasJobRecordNewRecord> aliased) {
        this(alias, aliased, null);
    }

    private MasJobRecordNew(Name alias, Table<MasJobRecordNewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mas_job_record_new</code> table reference
     */
    public MasJobRecordNew(String alias) {
        this(DSL.name(alias), MAS_JOB_RECORD_NEW);
    }

    /**
     * Create an aliased <code>public.mas_job_record_new</code> table reference
     */
    public MasJobRecordNew(Name alias) {
        this(alias, MAS_JOB_RECORD_NEW);
    }

    /**
     * Create a <code>public.mas_job_record_new</code> table reference
     */
    public MasJobRecordNew() {
        this(DSL.name("mas_job_record_new"), null);
    }

    public <O extends Record> MasJobRecordNew(Table<O> child, ForeignKey<O, MasJobRecordNewRecord> key) {
        super(child, key, MAS_JOB_RECORD_NEW);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MasJobRecordNewRecord> getPrimaryKey() {
        return Keys.MAS_JOB_RECORD_NEW_PK;
    }

    @Override
    public MasJobRecordNew as(String alias) {
        return new MasJobRecordNew(DSL.name(alias), this);
    }

    @Override
    public MasJobRecordNew as(Name alias) {
        return new MasJobRecordNew(alias, this);
    }

    @Override
    public MasJobRecordNew as(Table<?> alias) {
        return new MasJobRecordNew(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordNew rename(String name) {
        return new MasJobRecordNew(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordNew rename(Name name) {
        return new MasJobRecordNew(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordNew rename(Table<?> name) {
        return new MasJobRecordNew(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, MjrJobState, String, Instant, Instant, JSONB, String, String, MjrTargetType> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super String, ? super MjrJobState, ? super String, ? super Instant, ? super Instant, ? super JSONB, ? super String, ? super String, ? super MjrTargetType, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super String, ? super MjrJobState, ? super String, ? super Instant, ? super Instant, ? super JSONB, ? super String, ? super String, ? super MjrTargetType, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
