/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables;


import eu.dissco.backend.database.jooq.Keys;
import eu.dissco.backend.database.jooq.Public;
import eu.dissco.backend.database.jooq.enums.MjrJobState;
import eu.dissco.backend.database.jooq.enums.MjrTargetType;
import eu.dissco.backend.database.jooq.tables.records.MasJobRecordTmpRecord;

import java.time.Instant;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function10;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MasJobRecordTmp extends TableImpl<MasJobRecordTmpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mas_job_record_tmp</code>
     */
    public static final MasJobRecordTmp MAS_JOB_RECORD_TMP = new MasJobRecordTmp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MasJobRecordTmpRecord> getRecordType() {
        return MasJobRecordTmpRecord.class;
    }

    /**
     * The column <code>public.mas_job_record_tmp.job_id</code>.
     */
    public final TableField<MasJobRecordTmpRecord, String> JOB_ID = createField(DSL.name("job_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.job_state</code>.
     */
    public final TableField<MasJobRecordTmpRecord, MjrJobState> JOB_STATE = createField(DSL.name("job_state"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(eu.dissco.backend.database.jooq.enums.MjrJobState.class), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.mas_id</code>.
     */
    public final TableField<MasJobRecordTmpRecord, String> MAS_ID = createField(DSL.name("mas_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.time_started</code>.
     */
    public final TableField<MasJobRecordTmpRecord, Instant> TIME_STARTED = createField(DSL.name("time_started"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.time_completed</code>.
     */
    public final TableField<MasJobRecordTmpRecord, Instant> TIME_COMPLETED = createField(DSL.name("time_completed"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.mas_job_record_tmp.annotations</code>.
     */
    public final TableField<MasJobRecordTmpRecord, JSONB> ANNOTATIONS = createField(DSL.name("annotations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.mas_job_record_tmp.target_id</code>.
     */
    public final TableField<MasJobRecordTmpRecord, String> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.user_id</code>.
     */
    public final TableField<MasJobRecordTmpRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mas_job_record_tmp.target_type</code>.
     */
    public final TableField<MasJobRecordTmpRecord, MjrTargetType> TARGET_TYPE = createField(DSL.name("target_type"), SQLDataType.VARCHAR.asEnumDataType(eu.dissco.backend.database.jooq.enums.MjrTargetType.class), this, "");

    /**
     * The column <code>public.mas_job_record_tmp.batching_requested</code>.
     */
    public final TableField<MasJobRecordTmpRecord, Boolean> BATCHING_REQUESTED = createField(DSL.name("batching_requested"), SQLDataType.BOOLEAN, this, "");

    private MasJobRecordTmp(Name alias, Table<MasJobRecordTmpRecord> aliased) {
        this(alias, aliased, null);
    }

    private MasJobRecordTmp(Name alias, Table<MasJobRecordTmpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.mas_job_record_tmp</code> table reference
     */
    public MasJobRecordTmp(String alias) {
        this(DSL.name(alias), MAS_JOB_RECORD_TMP);
    }

    /**
     * Create an aliased <code>public.mas_job_record_tmp</code> table reference
     */
    public MasJobRecordTmp(Name alias) {
        this(alias, MAS_JOB_RECORD_TMP);
    }

    /**
     * Create a <code>public.mas_job_record_tmp</code> table reference
     */
    public MasJobRecordTmp() {
        this(DSL.name("mas_job_record_tmp"), null);
    }

    public <O extends Record> MasJobRecordTmp(Table<O> child, ForeignKey<O, MasJobRecordTmpRecord> key) {
        super(child, key, MAS_JOB_RECORD_TMP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MasJobRecordTmpRecord> getPrimaryKey() {
        return Keys.MAS_JOB_RECORD_TMP_PK;
    }

    @Override
    public MasJobRecordTmp as(String alias) {
        return new MasJobRecordTmp(DSL.name(alias), this);
    }

    @Override
    public MasJobRecordTmp as(Name alias) {
        return new MasJobRecordTmp(alias, this);
    }

    @Override
    public MasJobRecordTmp as(Table<?> alias) {
        return new MasJobRecordTmp(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordTmp rename(String name) {
        return new MasJobRecordTmp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordTmp rename(Name name) {
        return new MasJobRecordTmp(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MasJobRecordTmp rename(Table<?> name) {
        return new MasJobRecordTmp(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, MjrJobState, String, Instant, Instant, JSONB, String, String, MjrTargetType, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function10<? super String, ? super MjrJobState, ? super String, ? super Instant, ? super Instant, ? super JSONB, ? super String, ? super String, ? super MjrTargetType, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function10<? super String, ? super MjrJobState, ? super String, ? super Instant, ? super Instant, ? super JSONB, ? super String, ? super String, ? super MjrTargetType, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
