/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.tables;


import eu.dissco.backend.database.jooq.Keys;
import eu.dissco.backend.database.jooq.Public;
import eu.dissco.backend.database.jooq.enums.CollectionType;
import eu.dissco.backend.database.jooq.tables.records.VirtualCollectionRecord;

import java.time.Instant;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VirtualCollection extends TableImpl<VirtualCollectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.virtual_collection</code>
     */
    public static final VirtualCollection VIRTUAL_COLLECTION = new VirtualCollection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VirtualCollectionRecord> getRecordType() {
        return VirtualCollectionRecord.class;
    }

    /**
     * The column <code>public.virtual_collection.id</code>.
     */
    public final TableField<VirtualCollectionRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.virtual_collection.version</code>.
     */
    public final TableField<VirtualCollectionRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.virtual_collection.name</code>.
     */
    public final TableField<VirtualCollectionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.virtual_collection.collection_type</code>.
     */
    public final TableField<VirtualCollectionRecord, CollectionType> COLLECTION_TYPE = createField(DSL.name("collection_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(CollectionType.class), this, "");

    /**
     * The column <code>public.virtual_collection.created</code>.
     */
    public final TableField<VirtualCollectionRecord, Instant> CREATED = createField(DSL.name("created"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.virtual_collection.modified</code>.
     */
    public final TableField<VirtualCollectionRecord, Instant> MODIFIED = createField(DSL.name("modified"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.virtual_collection.tombstoned</code>.
     */
    public final TableField<VirtualCollectionRecord, Instant> TOMBSTONED = createField(DSL.name("tombstoned"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.virtual_collection.creator</code>.
     */
    public final TableField<VirtualCollectionRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.virtual_collection.data</code>.
     */
    public final TableField<VirtualCollectionRecord, JSONB> DATA = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "");

    private VirtualCollection(Name alias, Table<VirtualCollectionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VirtualCollection(Name alias, Table<VirtualCollectionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.virtual_collection</code> table reference
     */
    public VirtualCollection(String alias) {
        this(DSL.name(alias), VIRTUAL_COLLECTION);
    }

    /**
     * Create an aliased <code>public.virtual_collection</code> table reference
     */
    public VirtualCollection(Name alias) {
        this(alias, VIRTUAL_COLLECTION);
    }

    /**
     * Create a <code>public.virtual_collection</code> table reference
     */
    public VirtualCollection() {
        this(DSL.name("virtual_collection"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<VirtualCollectionRecord> getPrimaryKey() {
        return Keys.VIRTUAL_COLLECTION_PKEY;
    }

    @Override
    public VirtualCollection as(String alias) {
        return new VirtualCollection(DSL.name(alias), this);
    }

    @Override
    public VirtualCollection as(Name alias) {
        return new VirtualCollection(alias, this);
    }

    @Override
    public VirtualCollection as(Table<?> alias) {
        return new VirtualCollection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VirtualCollection rename(String name) {
        return new VirtualCollection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VirtualCollection rename(Name name) {
        return new VirtualCollection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VirtualCollection rename(Table<?> name) {
        return new VirtualCollection(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection where(Condition condition) {
        return new VirtualCollection(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VirtualCollection where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VirtualCollection where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VirtualCollection where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VirtualCollection where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VirtualCollection whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
