/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq.enums;


import eu.dissco.backend.database.jooq.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum JobState implements EnumType {

    SCHEDULED("SCHEDULED"),

    RUNNING("RUNNING"),

    FAILED("FAILED"),

    COMPLETED("COMPLETED");

    private final String literal;

    private JobState(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "job_state";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static JobState lookupLiteral(String literal) {
        return EnumType.lookupLiteral(JobState.class, literal);
    }
}
