/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq;


import eu.dissco.backend.database.jooq.tables.NewDigitalSpecimen;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NEW_DIGITAL_SPECIMEN_CREATED_IDX = Internal.createIndex(DSL.name("new_digital_specimen_created_idx"), NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN, new OrderField[] { NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN.CREATED }, false);
    public static final Index NEW_DIGITAL_SPECIMEN_ID_IDX = Internal.createIndex(DSL.name("new_digital_specimen_id_idx"), NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN, new OrderField[] { NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN.ID, NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN.CREATED }, false);
    public static final Index NEW_DIGITAL_SPECIMEN_PHYSICAL_SPECIMEN_ID_IDX = Internal.createIndex(DSL.name("new_digital_specimen_physical_specimen_id_idx"), NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN, new OrderField[] { NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN.PHYSICAL_SPECIMEN_ID }, false);
}
