/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq;


import eu.dissco.backend.database.jooq.tables.MachineAnnotationServices;
import eu.dissco.backend.database.jooq.tables.MasJobRecord;
import eu.dissco.backend.database.jooq.tables.NewAnnotation;
import eu.dissco.backend.database.jooq.tables.NewDigitalMediaObject;
import eu.dissco.backend.database.jooq.tables.NewDigitalSpecimen;
import eu.dissco.backend.database.jooq.tables.NewUser;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.machine_annotation_services</code>.
     */
    public static final MachineAnnotationServices MACHINE_ANNOTATION_SERVICES = MachineAnnotationServices.MACHINE_ANNOTATION_SERVICES;

    /**
     * The table <code>public.mas_job_record</code>.
     */
    public static final MasJobRecord MAS_JOB_RECORD = MasJobRecord.MAS_JOB_RECORD;

    /**
     * The table <code>public.new_annotation</code>.
     */
    public static final NewAnnotation NEW_ANNOTATION = NewAnnotation.NEW_ANNOTATION;

    /**
     * The table <code>public.new_digital_media_object</code>.
     */
    public static final NewDigitalMediaObject NEW_DIGITAL_MEDIA_OBJECT = NewDigitalMediaObject.NEW_DIGITAL_MEDIA_OBJECT;

    /**
     * The table <code>public.new_digital_specimen</code>.
     */
    public static final NewDigitalSpecimen NEW_DIGITAL_SPECIMEN = NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN;

    /**
     * The table <code>public.new_user</code>.
     */
    public static final NewUser NEW_USER = NewUser.NEW_USER;
}
