/*
 * This file is generated by jOOQ.
 */
package eu.dissco.backend.database.jooq;


import eu.dissco.backend.database.jooq.tables.NewAnnotation;
import eu.dissco.backend.database.jooq.tables.NewDigitalMediaObject;
import eu.dissco.backend.database.jooq.tables.NewDigitalSpecimen;
import eu.dissco.backend.database.jooq.tables.NewMapping;
import eu.dissco.backend.database.jooq.tables.NewSourceSystem;
import eu.dissco.backend.database.jooq.tables.OrganisationDo;
import eu.dissco.backend.database.jooq.tables.OrganisationDocument;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.new_annotation</code>.
     */
    public static final NewAnnotation NEW_ANNOTATION = NewAnnotation.NEW_ANNOTATION;

    /**
     * The table <code>public.new_digital_media_object</code>.
     */
    public static final NewDigitalMediaObject NEW_DIGITAL_MEDIA_OBJECT = NewDigitalMediaObject.NEW_DIGITAL_MEDIA_OBJECT;

    /**
     * The table <code>public.new_digital_specimen</code>.
     */
    public static final NewDigitalSpecimen NEW_DIGITAL_SPECIMEN = NewDigitalSpecimen.NEW_DIGITAL_SPECIMEN;

    /**
     * The table <code>public.new_mapping</code>.
     */
    public static final NewMapping NEW_MAPPING = NewMapping.NEW_MAPPING;

    /**
     * The table <code>public.new_source_system</code>.
     */
    public static final NewSourceSystem NEW_SOURCE_SYSTEM = NewSourceSystem.NEW_SOURCE_SYSTEM;

    /**
     * The table <code>public.organisation_do</code>.
     */
    public static final OrganisationDo ORGANISATION_DO = OrganisationDo.ORGANISATION_DO;

    /**
     * The table <code>public.organisation_document</code>.
     */
    public static final OrganisationDocument ORGANISATION_DOCUMENT = OrganisationDocument.ORGANISATION_DOCUMENT;
}
